# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0002_add_landing_page_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='concreterichtext',
            name='landing_page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teaching.LandingPage'),
        ),
    ]
